# Generated by Django 3.2.4 on 2021-06-20 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 15, 17, 15, 747760)),
        ),
    ]
