# Generated by Django 3.2.4 on 2021-06-16 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210615_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.AlterField(
            model_name='auction',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 20, 35, 30, 264987)),
        ),
    ]
