# Generated by Django 3.2.4 on 2021-06-26 19:19

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210620_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 19, 8, 158865)),
        ),
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ManyToManyField(blank=True, null=True, related_name='auctions_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
