# Generated by Django 3.2.4 on 2021-06-16 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210616_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 20, 37, 40, 904883)),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
