# Generated by Django 3.2.4 on 2021-06-26 19:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210626_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 19, 29, 4, 539931)),
        ),
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
