# Generated by Django 3.2.4 on 2021-06-16 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210616_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='auctions_with_category', to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 20, 50, 41, 719809)),
        ),
    ]
